### ISSUE TITLE
Add ellipsis on the Audit Logs table when the text of the cell is too long

### ISSUE THREAD

**Issue by YulyGP** [nexxtway/rainbow-modules#590]
**What exists:**
In the Audit Logs table, the text cell doesn't fit in the space when the text is too long. 
<img width="1430" alt="Screen Shot 2022-08-01 at 7 51 19 PM" src="https://user-images.githubusercontent.com/71304589/182268807-6d76a363-e1a3-4663-9f7b-26210701b3c0.png">

**What should be:**

- In the Audit Logs table, when the text is too long to fit in the cell, the system should be able to display an ellipsis at the end of the cell.
- When you hover over the cell with the long text and the ellipsis, the system should display a tooltip with all the info of the cell so that the user can read all the content that doesn't fit in the cell.

**Comment by LeandroTorresSicilia** [comment]
fixed by #592
